server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_fraud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 1

